service: personal-dashboard-api

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    noDeploy:
      - '*'

provider:
  name: aws
  runtime: python3.9
  region: us-west-1
  environment:
    WEATHER_API_KEY: ${env:WEATHER_API_KEY}
    # Add other environment variables as needed

functions:
  getWeather:
    handler: services/get-weather/handler.get_weather
    # This explicitly tells the plugin where to find this function's code and requirements
    module: services/get-weather
    events:
      - http:
          path: weather
          method: get
          cors: true